In [28]:
#import required data
import numpy as np,pandas as pd,matplotlib.pyplot as pyplot
from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn.model_selection import train_test_split

#load iris data and create dataset
iris_dataset = load_iris()
x_train,x_test,y_train,y_test = train_test_split(iris_dataset["data"],iris_dataset["target"],random_state=0)
print(iris_dataset["data"][:5])
print(iris_dataset["target"][:5])

#KneighborsClassifier
kn = KNeighborsClassifier()
kn.fit(x_train,y_train)

prediction1 = kn.predict(x_train)
prediction2 = kn.predict(x_test)

print(prediction)

print("Training Accuracy: ",accuracy_score(y_train,prediction1))
print("Testing Accuracy: ",accuracy_score(y_test,prediction2))
print("Training Confusion Matrix is: ",confusion_matrix(y_train,prediction1))
print("Testing Confucion Matrix is: ",confusion_matrix(y_test,prediction2))

target_names = iris_dataset.target_names
for pred,actual in zip(prediction,y_test):
    print("predicton is:"+str(target_names[pred])+", Actual is "+str(target_names[actual]))

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]
[2]
Training Accuracy:  0.9732142857142857
Testing Accuracy:  0.9736842105263158
Training Confusion Matrix is:  [[37  0  0]
 [ 0 32  2]
 [ 0  1 40]]
Testing Confucion Matrix is:  [[13  0  0]
 [ 0 15  1]
 [ 0  0  9]]
predicton is:virginica, Actual is virginica
